-- ONE STYLE FOREVER
-- Core e-commerce order storage for Supabase (PostgreSQL)

create extension if not exists pgcrypto;

create table if not exists public.orders (
  id text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  customer_address text not null,
  customer_comment text,
  total numeric(12, 2) not null check (total >= 0),
  status text not null check (status in ('new', 'confirmed', 'shipped', 'delivered', 'cancelled', 'returned')),
  source text not null default 'web',
  telegram_sent boolean not null default false,
  email_sent boolean not null default false
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id text not null,
  title text not null,
  price numeric(12, 2) not null check (price >= 0),
  quantity integer not null check (quantity > 0),
  selected_size text
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  status text not null check (status in ('new', 'confirmed', 'shipped', 'delivered', 'cancelled', 'returned')),
  changed_at timestamptz not null default now(),
  note text,
  actor text
);

create index if not exists idx_orders_created_at_desc on public.orders (created_at desc);
create index if not exists idx_orders_status on public.orders (status);
create index if not exists idx_order_items_order_id on public.order_items (order_id);
create index if not exists idx_order_status_history_order_id on public.order_status_history (order_id);
create index if not exists idx_order_status_history_changed_at on public.order_status_history (changed_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_orders_set_updated_at on public.orders;
create trigger trg_orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;

-- This project uses server-only access with SERVICE ROLE key.
-- If you need client-side direct access later, add explicit RLS policies.
