-- ONE STYLE FOREVER
-- Core e-commerce order storage for Supabase (PostgreSQL)

create extension if not exists pgcrypto;
create sequence if not exists public.order_number_seq start 1 increment 1 minvalue 1;

create table if not exists public.orders (
  id text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  customer_user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  customer_address text not null,
  customer_comment text,
  total numeric(12, 2) not null check (total >= 0),
  payment_method text not null default 'cash_on_delivery' check (payment_method in ('card_online', 'phone_transfer', 'cash_on_delivery')),
  payment_status text not null default 'cash_on_delivery' check (payment_status in ('pending', 'paid', 'cash_on_delivery')),
  status text not null check (status in ('new', 'confirmed', 'assembled', 'shipped', 'delivered', 'cancelled', 'returned')),
  source text not null default 'web',
  telegram_sent boolean not null default false,
  email_sent boolean not null default false
);

alter table public.orders
  add column if not exists payment_method text not null default 'cash_on_delivery';
alter table public.orders
  add column if not exists payment_status text not null default 'cash_on_delivery';
alter table public.orders
  add column if not exists customer_user_id uuid references auth.users(id) on delete set null;

create table if not exists public.customer_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id text not null,
  title text not null,
  price numeric(12, 2) not null check (price >= 0),
  quantity integer not null check (quantity > 0),
  selected_size text
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  status text not null check (status in ('new', 'confirmed', 'assembled', 'shipped', 'delivered', 'cancelled', 'returned')),
  changed_at timestamptz not null default now(),
  note text,
  actor text
);

create table if not exists public.product_inventory (
  product_id text not null,
  size text not null check (size in ('S', 'M', 'L')),
  quantity integer not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now(),
  primary key (product_id, size)
);

create table if not exists public.inventory_change_log (
  id bigint generated by default as identity primary key,
  product_id text not null,
  size text not null check (size in ('S', 'M', 'L')),
  prev_quantity integer not null check (prev_quantity >= 0),
  next_quantity integer not null check (next_quantity >= 0),
  delta integer not null,
  changed_at timestamptz not null default now(),
  actor text,
  source text,
  reason text
);

alter table public.inventory_change_log
  add column if not exists source text;
alter table public.inventory_change_log
  add column if not exists reason text;

create table if not exists public.product_overrides (
  product_id text primary key,
  price numeric(12, 2),
  badge text check (badge in ('NEW', 'HOT')),
  is_active boolean,
  title_ru text,
  title_ro text,
  title_en text,
  short_description_ru text,
  short_description_ro text,
  short_description_en text,
  updated_at timestamptz not null default now(),
  updated_by text
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor text not null,
  action text not null,
  target_type text,
  target_id text,
  details jsonb
);

create table if not exists public.order_auth_codes (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  phone_norm text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 5 check (max_attempts > 0),
  delivery_channel text not null default 'telegram' check (delivery_channel in ('telegram', 'sms')),
  last_sent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, phone_norm)
);

create table if not exists public.customer_telegram_contacts (
  phone_norm text primary key,
  telegram_chat_id text not null,
  telegram_username text,
  telegram_first_name text,
  telegram_last_name text,
  linked_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_link_tokens (
  token text primary key,
  order_id text not null references public.orders(id) on delete cascade,
  phone_norm text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.checkout_drafts (
  draft_key text primary key,
  phone_norm text,
  draft_data jsonb not null default '{}'::jsonb,
  saved_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id text not null,
  customer_phone text not null,
  selected_size text,
  rating integer not null check (rating between 1 and 5),
  review_text text not null,
  photo_urls jsonb not null default '[]'::jsonb,
  verified boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, product_id)
);

create index if not exists idx_orders_created_at_desc on public.orders (created_at desc);
create index if not exists idx_orders_status on public.orders (status);
create index if not exists idx_orders_customer_user_id on public.orders (customer_user_id, created_at desc);
create index if not exists idx_order_items_order_id on public.order_items (order_id);
create index if not exists idx_order_status_history_order_id on public.order_status_history (order_id);
create index if not exists idx_order_status_history_changed_at on public.order_status_history (changed_at desc);
create index if not exists idx_product_inventory_product_id on public.product_inventory (product_id);
create index if not exists idx_inventory_change_log_product on public.inventory_change_log (product_id);
create index if not exists idx_inventory_change_log_changed_at on public.inventory_change_log (changed_at desc);
create index if not exists idx_inventory_change_log_source on public.inventory_change_log (source);
create index if not exists idx_product_overrides_updated_at on public.product_overrides (updated_at desc);
create index if not exists idx_admin_audit_log_created_at on public.admin_audit_log (created_at desc);
create index if not exists idx_admin_audit_log_action on public.admin_audit_log (action);
create index if not exists idx_order_auth_codes_order_phone on public.order_auth_codes (order_id, phone_norm);
create index if not exists idx_order_auth_codes_expires_at on public.order_auth_codes (expires_at);
create index if not exists idx_customer_telegram_contacts_chat on public.customer_telegram_contacts (telegram_chat_id);
create index if not exists idx_telegram_link_tokens_order_phone on public.telegram_link_tokens (order_id, phone_norm);
create index if not exists idx_telegram_link_tokens_expires on public.telegram_link_tokens (expires_at);
create index if not exists idx_checkout_drafts_saved_at on public.checkout_drafts (saved_at desc);
create index if not exists idx_checkout_drafts_phone_norm on public.checkout_drafts (phone_norm, saved_at desc);
create index if not exists idx_product_reviews_product_created on public.product_reviews (product_id, created_at desc);
create index if not exists idx_product_reviews_order_product on public.product_reviews (order_id, product_id);
create index if not exists idx_product_reviews_customer_phone on public.product_reviews (customer_phone, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.next_order_number()
returns bigint
language sql
as $$
  select nextval('public.order_number_seq');
$$;

alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders
  add constraint orders_status_check
  check (status in ('new', 'confirmed', 'assembled', 'shipped', 'delivered', 'cancelled', 'returned'));

alter table public.orders drop constraint if exists orders_payment_method_check;
alter table public.orders
  add constraint orders_payment_method_check
  check (payment_method in ('card_online', 'phone_transfer', 'cash_on_delivery'));

alter table public.orders drop constraint if exists orders_payment_status_check;
alter table public.orders
  add constraint orders_payment_status_check
  check (payment_status in ('pending', 'paid', 'cash_on_delivery'));

alter table public.order_status_history drop constraint if exists order_status_history_status_check;
alter table public.order_status_history
  add constraint order_status_history_status_check
  check (status in ('new', 'confirmed', 'assembled', 'shipped', 'delivered', 'cancelled', 'returned'));

drop trigger if exists trg_orders_set_updated_at on public.orders;
create trigger trg_orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

drop trigger if exists trg_inventory_set_updated_at on public.product_inventory;
create trigger trg_inventory_set_updated_at
before update on public.product_inventory
for each row
execute function public.set_updated_at();

drop trigger if exists trg_product_overrides_set_updated_at on public.product_overrides;
create trigger trg_product_overrides_set_updated_at
before update on public.product_overrides
for each row
execute function public.set_updated_at();

drop trigger if exists trg_order_auth_codes_set_updated_at on public.order_auth_codes;
create trigger trg_order_auth_codes_set_updated_at
before update on public.order_auth_codes
for each row
execute function public.set_updated_at();

drop trigger if exists trg_customer_telegram_contacts_set_updated_at on public.customer_telegram_contacts;
create trigger trg_customer_telegram_contacts_set_updated_at
before update on public.customer_telegram_contacts
for each row
execute function public.set_updated_at();

drop trigger if exists trg_checkout_drafts_set_updated_at on public.checkout_drafts;
create trigger trg_checkout_drafts_set_updated_at
before update on public.checkout_drafts
for each row
execute function public.set_updated_at();

drop trigger if exists trg_customer_profiles_set_updated_at on public.customer_profiles;
create trigger trg_customer_profiles_set_updated_at
before update on public.customer_profiles
for each row
execute function public.set_updated_at();

drop trigger if exists trg_product_reviews_set_updated_at on public.product_reviews;
create trigger trg_product_reviews_set_updated_at
before update on public.product_reviews
for each row
execute function public.set_updated_at();

create or replace function public.reserve_order_stock(order_items jsonb)
returns void
language plpgsql
as $$
declare
  item jsonb;
  v_product_id text;
  v_size text;
  v_quantity integer;
  current_qty integer;
begin
  if jsonb_typeof(order_items) <> 'array' then
    raise exception 'invalid_payload';
  end if;

  -- Lock rows and validate availability first.
  for item in select * from jsonb_array_elements(order_items)
  loop
    v_product_id := coalesce(item->>'product_id', '');
    v_size := coalesce(item->>'size', '');
    v_quantity := coalesce((item->>'quantity')::integer, 0);

    if v_product_id = '' or v_size = '' or v_quantity <= 0 then
      raise exception 'invalid_order_item';
    end if;

    select quantity
      into current_qty
      from public.product_inventory
      where product_id = v_product_id and size = v_size
      for update;

    if not found then
      raise exception 'out_of_stock:missing_%_%', v_product_id, v_size;
    end if;

    if current_qty < v_quantity then
      raise exception 'out_of_stock:insufficient_%_%', v_product_id, v_size;
    end if;
  end loop;

  -- Apply decrement only after all checks pass.
  for item in select * from jsonb_array_elements(order_items)
  loop
    v_product_id := item->>'product_id';
    v_size := item->>'size';
    v_quantity := (item->>'quantity')::integer;

    update public.product_inventory
    set quantity = quantity - v_quantity
    where product_id = v_product_id and size = v_size;
  end loop;
end;
$$;

create or replace function public.restore_order_stock(order_items jsonb)
returns void
language plpgsql
as $$
declare
  item jsonb;
  v_product_id text;
  v_size text;
  v_quantity integer;
begin
  if jsonb_typeof(order_items) <> 'array' then
    raise exception 'invalid_payload';
  end if;

  for item in select * from jsonb_array_elements(order_items)
  loop
    v_product_id := coalesce(item->>'product_id', '');
    v_size := coalesce(item->>'size', '');
    v_quantity := coalesce((item->>'quantity')::integer, 0);

    if v_product_id = '' or v_size = '' or v_quantity <= 0 then
      raise exception 'invalid_order_item';
    end if;

    update public.product_inventory
    set quantity = quantity + v_quantity
    where product_id = v_product_id and size = v_size;
  end loop;
end;
$$;

insert into public.product_inventory (product_id, size, quantity)
values
  ('white-halfzip-osf', 'S', 8),
  ('white-halfzip-osf', 'M', 10),
  ('white-halfzip-osf', 'L', 7),
  ('black-halfzip-osf', 'M', 6),
  ('black-halfzip-osf', 'L', 5),
  ('black-hoodie-osf', 'S', 6),
  ('black-hoodie-osf', 'M', 8),
  ('black-hoodie-osf', 'L', 7),
  ('white-hoodie-osf', 'S', 5),
  ('white-hoodie-osf', 'M', 7),
  ('white-hoodie-osf', 'L', 6),
  ('black-polo-osf', 'M', 9),
  ('black-polo-osf', 'L', 9),
  ('white-polo-osf', 'S', 8),
  ('white-polo-osf', 'M', 10),
  ('white-polo-osf', 'L', 8)
on conflict (product_id, size) do nothing;

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;
alter table public.product_inventory enable row level security;
alter table public.inventory_change_log enable row level security;
alter table public.product_overrides enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.order_auth_codes enable row level security;
alter table public.customer_telegram_contacts enable row level security;
alter table public.telegram_link_tokens enable row level security;
alter table public.checkout_drafts enable row level security;
alter table public.product_reviews enable row level security;
alter table public.customer_profiles enable row level security;

-- This project uses server-only access with SERVICE ROLE key.
-- If you need client-side direct access later, add explicit RLS policies.
